name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Code download karo
      - name: ğŸ— Setup Repo
        uses: actions/checkout@v3

      # 2. Node.js install karo
      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      # 3. YAHAN CHANGE HAI: Hum khud EAS install karenge (Plugin nahi use karenge)
      - name: ğŸ“¦ Install EAS CLI Manually
        run: npm install -g eas-cli

      # 4. Dependencies install karo
      - name: ğŸ“¦ Install Project Dependencies
        run: npm install

      # 5. Login karo (Secret Token se)
      - name: ğŸ”“ Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas-cli login --token $EXPO_TOKEN

      # 6. APK Banao
      - name: ğŸš€ Build APK
        run: npx eas-cli build --platform android --profile preview --non-interactive
