name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Code Download
      - name: ğŸ— Setup Repo
        uses: actions/checkout@v3

      # 2. Node JS Install
      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      # 3. EAS CLI Install (Global) - Ye line error hatayegi
      - name: ğŸ“¦ Install EAS CLI
        run: npm install -g eas-cli

      # 4. Project Files Install
      - name: ğŸ“¦ Install Dependencies
        run: npm install

      # 5. Build Command (Direct Token Injection)
      - name: ğŸš€ Build APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas-cli build --platform android --profile preview --non-interactive
