name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup Repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      # ğŸ‘‡ STEP 1: HUM KHUD INSTALL KARENGE EAS
      - name: ğŸ“¦ Install EAS CLI
        run: npm install -g eas-cli

      # ğŸ‘‡ STEP 2: PROJECT DEPENDENCIES
      - name: ğŸ“¦ Install Dependencies
        run: npm install

      # ğŸ‘‡ STEP 3: LOGIN KARENGE (Token se)
      - name: ğŸ”“ Login to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas-cli login --token $EXPO_TOKEN

      # ğŸ‘‡ STEP 4: BUILD BANAYENGE
      - name: ğŸš€ Build APK
        run: npx eas-cli build --platform android --profile preview --non-interactive
